### ISSUE TITLE
PSR-7 Compliance

### ISSUE THREAD

**Issue by DaGhostman** [mrjgreen/phroute#20]
Would a PSR-7 request be appropriate?

I think, that having a PSR-7 compliant method will make it easier for implementing #5 Sub-domain routing as PSR-7 server request object should contain all the necessary information for the dispatcher to do its work?

I was thinking of making a PR for a method dispatchPSR (although it looks fugly..) so that such implementation does not break existing implementations using Phroute.

**Comment by mrjgreen** [comment]
Yeah I like this idea - I hadn't thought of going down that route. I'd be really happy to see your ideas on how it could work!

**Comment by frederikbosch** [comment]
:+1: 

@DaGhostman Maybe this can be added to Phroute v3? The current PSR-7 is in review again, so it will take some time before there will be actual libraries that have full and stable support for it. Therefore, there is no need to rush with this. And I think dispatchPSR is fugly indeed and not necessary if we just bump the major version number one up.

**Comment by DaGhostman** [comment]
@frederikbosch Yeah, you are right. It seems that quite some time will pass until the PSR gets accepted.

**Comment by frederikbosch** [comment]
@DaGhostman There is already [a router supporting PSR-7](https://github.com/auraphp/Aura.Router/tree/3.x). Maybe it is not a bad idea after all to work on this.
