### ISSUE TITLE
Prefix routes

### ISSUE THREAD

**Issue by mrjulio** [mrjgreen/phroute#26]
Is there a way to have a prefix for routes inside a group instead of writing it manually ?
For example if I have http://website.com/admin/* for backend.

**Comment by mrjgreen** [comment]
Yes! You can do it like this:

~~~PHP
$collector = new Phroute\Phroute\RouteCollector();

$collector->group(array('prefix' => 'admin'), function($collector){

    $collector->get('pages', function(){
        return 'page management';
    });

    $collector->get('products', function(){
        return 'product management';
    });

    $collector->get('orders', function(){
        return 'order management';
    });
});

$dispatcher =  new Phroute\Phroute\Dispatcher($collector->getData());

$dispatcher->dispatch('GET', '/admin/pages'); // "page management"
$dispatcher->dispatch('GET', '/admin/orders'); // "order management"
~~~

**Comment by mrjgreen** [comment]
I've added an example to the readme here https://github.com/mrjgreen/phroute#prefix-groups
and also added a new "examples" folder in the project root.

Thanks for the feedback, and sorry its taken so long to reply!

**Comment by iuliann** [comment]
Thanks! 
I'm using the library for my framework as the default routing manager.
I managed to use admin.domain.com so far but it's great that now I can use it with groups.
