### ISSUE TITLE
New tagged release with the group prefix?

### ISSUE THREAD

**Issue by magnus-eriksson** [mrjgreen/phroute#33]
Any chance we can get a new tagged release with the group prefix functionality? 
It's awesome and I don't really like to use dev-master.

**Comment by mrjgreen** [comment]
Yeah sure! Will do it shortly. Sorry about that.

Cheers
Joe Green

**Comment by mrjgreen** [comment]
Done

**Comment by magnus-eriksson** [comment]
Great! Thanks. :)

-----Original Message-----
