### ISSUE TITLE
Add "prefix" option like in Laravel

### ISSUE THREAD

**Issue by zaksmok** [mrjgreen/phroute#4]
Add it to filters and groups

**Comment by DaGhostman** [comment]
Why would filters need prefixes? @zaksmok

**Comment by mrjgreen** [comment]
I like the idea of this, but I'm not yet convinced it needs baking it into the router... It seems this could be implemented reasonably easily in the client code. I'd be happy to see a PR for this though if anybody would like to submit one. If there's further interest in this I'll consider adding it to the "todo list".

**Comment by DaGhostman** [comment]
PR is on it's way :)
