### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by darklove2501** [mrjgreen/phroute#40]
This is my .htaccess.
I put router at index.php
But it doesn't works

RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ /index.php [NC,L,QSA]

**Comment by mrjgreen** [comment]
Hi
I afraid I haven't used apache for a long time so I can't offer an exact solution. Can you see which part of your set up is not working? Are you seeing error messages on your screen/terminal? Have you checked your apache error logs? Are you getting 404s? 500s? PHP Exceptions?

It would be good if you could provide a bit more information when submitting a request for help. This is a really good (but a bit long) essay on how to effectively submit bug requests http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

Thanks!

**Comment by dperezmavro** [comment]
I have run into this exact same issue. In my case everything works perfectly if I run php -S localhost:8080, but as soon as I drop the application in the /var/www/html directory and let apache be the web server, then it looks like it resolves all routes to physical paths on disk. Out  of curiosity @mrjgreen , what do you use to make phroute work without the PHP server (such as a production environment)?
