### ISSUE TITLE
Does phroute support namespaced controller?

### ISSUE THREAD

**Issue by javasworks** [mrjgreen/phroute#42]
I can't find it in documentation. Would be nice if it supports namespaced controller.

**Comment by mrjgreen** [comment]
Sure! You can just add the namespace like this:  `$router->controller('/controller', 'MyApp\\Test');`

I've update the readme to include this example: https://github.com/mrjgreen/phroute/blob/master/README.md#controllers

Thanks for the question! Hope I've helped :)
