### ISSUE TITLE
I get a blank page

### ISSUE THREAD

**Issue by vladvisinescu** [mrjgreen/phroute#48]
After installing this package, which seems to be the most simple to use of all, I have created this file `index.php`:

```
$router = new \Phroute\Phroute\RouteCollector();

$router->get('/home', function () {
    return 'hello world';
});
```

and all I get is a white page. The `htaccess` file looks like this:

```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . index.php [L]
```

**Comment by mrjgreen** [comment]
Are you dispatching the route as per the example here? https://github.com/mrjgreen/phroute/blob/master/examples/simple.php#L24

If so and you are still getting a blank page you will need to make sure you have PHP's display_errors ini setting configured correctly.
