### ISSUE TITLE
Query string in request exception

### ISSUE THREAD

**Issue by a-x-** [mrjgreen/phroute#6]
// Excuse my beginner's English

There is possible bug.

My route: `get /api/account/{user_id:i}/token/`

My request: `get /api/account/285/token/?name=info-product`

Exception: `Route api/account/285/token/?name=info-product does not exist`

Thanks!

**Comment by semau** [comment]
Please add this line to README, it's very helpful one :)
        $response = $dispatcher->dispatch($_SERVER['REQUEST_METHOD'], parse_url($_SERVER["REQUEST_URI"])['path']);
