### ISSUE TITLE
Bug with PHP 8.1 with RouteCollector class

### ISSUE THREAD

**Issue by Sleon4** [mrjgreen/phroute#99]
This problem is occurring in an environment where it was upgraded to PHP 8.1, the trim function of this class cannot trim a null data type, with the new version of PHP a different cast is required for a null data.
For the project that I am developing, I had to modify the phroute code to be able to make it run.

original function:
/**
      * @param $route
      * @return string
      */
     private function trim($route)
     {
         return trim($route, '/');
     }

corrected function
/**
      * @param $route
      * @return string
      */
     private function trim($route)
     {
         return trim($route === null ? '' : $route, '/');
     }

**Comment by mrjgreen** [comment]
Hi - thanks for raising this issue.

I've fixed the issue on master, if you wouldn't mind taking a look and making sure it's solved your issue, then I will create a new release and close this PR.

**Comment by Sleon4** [comment]
> Hi - thanks for raising this issue.
> 
> I've fixed the issue on master, if you wouldn't mind taking a look and making sure it's solved your issue, then I will create a new release and close this PR.

Sure, I'll run tests and put it in writing if it's correct.

**Comment by Sleon4** [comment]
> 

I tried to see the changes by installing the library from composer require phroute/phroute and I was not successful, it still downloads the same version with the BUG.
I decided to do the switch manually with the library installed and it works fine in a PHP 8.1 environment.

**Comment by Sleon4** [comment]
> > > Hi - thanks for raising this issue.
> > > I've fixed the issue on master, if you wouldn't mind taking a look and making sure it's solved your issue, then I will create a new release and close this PR.
> > 
> > 

I tried to see the changes by installing the library from composer require phroute/phroute and I was not successful, it still downloads the same version with the BUG. I decided to do the switch manually with the library installed and it works fine in a PHP 8.1 environment.

**Comment by Sleon4** [comment]
I have done multiple tests in different environments, both in windows and linux, this runs perfectly, thank you very much for your help.
